### ISSUE TITLE
NecTAR tutorial on OpenStack CLI's and failure on installation of openstack_client

### ISSUE THREAD

**Issue by young-acecrc** [NeCTAR-RC/tutorials#116]
Problems installing openstackclient on CentOS_7  
Eventually installed --  apprently successfully
Errors when calling openstackclient

First a trivial comment:
Item 3.  Using dedicated clients:
Tutorial lists clients as:  nova, glance, swift, gnocchi and murano.
Whereas the OPENSTACK RC file lists the clients as: 
(code-named nova, glance, keystone, swift, cinder, and neutron)

Instructions for installation are confusing and appear to have some deficiencies.

Item 2.
My view is need to install: python3 versions of everything.  So for CentOS_7:
yum install python3-devel python3-pip   (Tutorial has python-devel)
To install the openstackclient, command is given as either: 
pip install python-openstackclient   or 
yum install python3-openstackclient

There is no python3-openstackclient!  
Only python-openstackclient 

I found yum install python-openstackclient  unsuccessful

For the pip install it needs to be pip3 not pip, and use of pip as root  gives severe warning as to its use in this mode.

Recommended usage for pip is:
python3 -m pip ....

To get openstackclient installation to work I needed to install rust, python-setuptools, and upgrade pip as:
yum install rust
yum install python-setuptools
python3 -m pip install --upgrade pip

Then invoke command:
python3 -m pip install python-openstackclient

This appears to conclude successfully.

But gives errors as soon as openstackclient is invoked:

[ec2-user@ny-train ~]$ openstack help
Traceback (most recent call last):
  File "/usr/local/bin/openstack", line 5, in <module>
    from openstackclient.shell import main
  File "/usr/local/lib/python3.6/site-packages/openstackclient/shell.py", line 23, in <module>
    from osc_lib import shell
  File "/usr/local/lib/python3.6/site-packages/osc_lib/shell.py", line 32, in <module>
    from osc_lib.cli import client_config as cloud_config
  File "/usr/local/lib/python3.6/site-packages/osc_lib/cli/client_config.py", line 18, in <module>
    from openstack.config import exceptions as sdk_exceptions
  File "/usr/local/lib/python3.6/site-packages/openstack/__init__.py", line 58, in <module>
    import openstack.connection
  File "/usr/local/lib/python3.6/site-packages/openstack/connection.py", line 217, in <module>
    from openstack import _services_mixin
  File "/usr/local/lib/python3.6/site-packages/openstack/_services_mixin.py", line 6, in <module>
    from openstack.block_storage import block_storage_service
  File "/usr/local/lib/python3.6/site-packages/openstack/block_storage/block_storage_service.py", line 14, in <module>
    from openstack.block_storage.v3 import _proxy as _v3_proxy
  File "/usr/local/lib/python3.6/site-packages/openstack/block_storage/v3/_proxy.py", line 37, in <module>
    class Proxy(_base_proxy.BaseBlockStorageProxy):
  File "/usr/local/lib/python3.6/site-packages/openstack/block_storage/v3/_proxy.py", line 1592, in Proxy
    ignore_missing: ty.Literal[True] = True,
AttributeError: module 'typing' has no attribute 'Literal'
[ec2-user@ny-train ~]$

**Comment by sorrison** [comment]
Hi there, Centos 7 is end of life in just over a month so we aren't going to support this operating system.
Thanks
